name: Morning Agent

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'  # 6:30 AM AWST

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: echo "👋 Hello from GitHub Actions!"
